const constants = {

  // App
  REDIRECT_APP: 'REDIRECT_APP',
  RESET_REDIRECT_PATH: 'RESET_REDIRECT_PATH',
  ASYNC_START: 'ASYNC_START',
  ASYNC_FINISH: 'ASYNC_FINISH',
  MAKE_ERROR_MESSAGE: 'MAKE_ERROR_MESSAGE',
  DELETE_ERROR_MESSAGE: 'DELETE_ERROR_MESSAGE',

  // Color Organizer
  ADD_COLOR: 'ADD_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  TOGGLE_ADD_COLOR_FORM: 'TOGGLE_ADD_COLOR_FORM',

  // Wikis
  GET_ALL_WIKI: 'GET_ALL_WIKI',
  CREATE_WIKI: 'CREATE_WIKI',
  UPDATE_WIKI: 'UPDATE_WIKI',
  DELETE_WIKI: 'DELETE_WIKI'
}

export default constants
