const constants = {

  // App
  REDIRECT_APP: 'REDIRECT_APP',
  RESET_REDIRECT_PATH: 'RESET_REDIRECT_PATH',
  START_LOADING: 'START_LOADING',
  FINISH_LOADING: 'FINISH_LOADING',

  // Color Organizer
  ADD_COLOR: 'ADD_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  TOGGLE_ADD_COLOR_FORM: 'TOGGLE_ADD_COLOR_FORM',

  // Wikis
  GET_ALL_WIKI: 'GET_ALL_WIKI',
  CREATE_WIKI: 'CREATE_WIKI',
  UPDATE_WIKI: 'UPDATE_WIKI',
  REMOVE_WIKI: 'REMOVE_WIKI'
}

export default constants
