const constants = {

  // App
  REDIRECT_APP: 'REDIRECT_APP',
  RESET_REDIRECT_PATH: 'RESET_REDIRECT_PATH',

  // Color Organizer
  ADD_COLOR: 'ADD_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  TOGGLE_ADD_COLOR_FORM: 'TOGGLE_ADD_COLOR_FORM',

  // Wikis
  CREATE_WIKI: 'CREATE_WIKI',
  REMOVE_WIKI: 'REMOVE_WIKI'
}

export default constants
